[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"
